In [1]:
import pandas as pd

In [2]:
stations = pd.read_csv("data/raw/stations_metadaten.csv")
stations.head()

,id,Synopstationsnummer,Stationsname,Länge [°E],Breite [°N],Höhe [m],Startdatum,Enddatum,Bundesland,Sonnenschein,Globalstrahlung,Synop,Verknüpfungsnummer,Startdatum Teilzeitreihe,Enddatum Teilzeitreihe,zusammengesetzt
0,1,NaN,Aflenz,15.24069,47.54594,783.2,1983-05-01 00:00:00+00:00,2100-12-31 00:00:00+00:00,Steiermark,True,True,NaN,NaN,NaN,NaN,ja
1,2,NaN,Aigen im Ennstal,14.13826,47.53278,641.0,1939-03-01 00:00:00+00:00,2100-12-31 00:00:00+00:00,Steiermark,True,True,NaN,NaN,NaN,NaN,ja
2,3,NaN,Allentsteig,15.36694,48.69083,598.8,1983-10-01 00:00:00+00:00,2100-12-31 00:00:00+00:00,Niederösterreich,True,True,NaN,NaN,NaN,NaN,ja
3,4,NaN,Amstetten,14.89500,48.10889,266.0,1936-01-01 00:00:00+00:00,2100-12-31 00:00:00+00:00,Niederösterreich,True,True,NaN,NaN,NaN,NaN,ja
4,5,NaN,Bad Aussee,13.75844,47.61050,743.1,1983-09-01 00:00:00+00:00,2100-12-31 00:00:00+00:00,Steiermark,True,False,NaN,NaN,NaN,NaN,ja

In [3]:
stations.info()

<class 'pandas.DataFrame'>
RangeIndex: 1144 entries, 0 to 1143
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        1144 non-null   int64
 1   Synopstationsnummer       338 non-null    float64
 2   Stationsname              1144 non-null   str
 3   Länge [°E]                1144 non-null   float64
 4   Breite [°N]               1144 non-null   float64
 5   Höhe [m]                  1144 non-null   float64
 6   Startdatum                1144 non-null   str
 7   Enddatum                  1144 non-null   str
 8   Bundesland                1144 non-null   str
 9   Sonnenschein              1144 non-null   bool
 10  Globalstrahlung           1144 non-null   bool
 11  Synop                     0 non-null      float64
 12  Verknüpfungsnummer        594 non-null    float64
 13  Startdatum Teilzeitreihe  594 non-null    str
 14  Enddatum Teilzeitreihe    404 non-null    str
 15  zusammengesetzt           1144 non-null   str
dtypes: bool(2), float64(6), int64(1), str(7)
memory usage: 127.5 KB

In [4]:
tirol_stations = stations[stations["Bundesland"] == "Tirol"]

tirol_stations[[
    "id",
    "Stationsname",
    "Höhe [m]",
    "Startdatum",
    "Enddatum"
]].head(10)

,id,Stationsname,Höhe [m],Startdatum,Enddatum
15,16,Brenner,1412.0,1948-01-01 00:00:00+00:00,2100-12-31 00:00:00+00:00
19,20,Ehrwald,982.0,1972-08-01 00:00:00+00:00,2100-12-31 00:00:00+00:00
27,28,Galtür,1587.0,1901-01-01 00:00:00+00:00,2100-12-31 00:00:00+00:00
37,38,Imst,773.0,1936-01-01 00:00:00+00:00,2100-12-31 00:00:00+00:00
38,39,Innsbruck Universität,578.0,1877-01-01 00:00:00+00:00,2100-12-31 00:00:00+00:00
40,42,Jenbach,529.0,1955-04-01 00:00:00+00:00,2100-12-31 00:00:00+00:00
41,43,Kals,1352.4,1951-05-01 00:00:00+00:00,2100-12-31 00:00:00+00:00
48,50,Landeck,795.6,1946-02-01 00:00:00+00:00,2100-12-31 00:00:00+00:00
53,55,Lienz,661.0,1880-01-01 00:00:00+00:00,2100-12-31 00:00:00+00:00
59,61,Mayrhofen,640.0,1936-01-01 00:00:00+00:00,2100-12-31 00:00:00+00:00

In [5]:
klima = pd.read_csv("data/raw/Tirol_Stationsdaten-v2 (1 m)_ Qualitätsgeprüfte Stationsdaten.csv")

klima.head()

,time,station,tl_mittel,tlmax_mittel,tlmin_mittel,tage_frost,shneu_manu,tage_schdecke,sh_manu_max,rr,tage_festrrp,substation
0,1900-01-01T00:00+00:00,8501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1900-01-01T00:00+00:00,8800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1900-01-01T00:00+00:00,8805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1900-01-01T00:00+00:00,8806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1900-01-01T00:00+00:00,8807,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
klima.info()

<class 'pandas.DataFrame'>
RangeIndex: 267696 entries, 0 to 267695
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   time           267696 non-null  str
 1   station        267696 non-null  int64
 2   tl_mittel      67651 non-null   float64
 3   tlmax_mittel   64607 non-null   float64
 4   tlmin_mittel   64579 non-null   float64
 5   tage_frost     64278 non-null   float64
 6   shneu_manu     36277 non-null   float64
 7   tage_schdecke  56856 non-null   float64
 8   sh_manu_max    56863 non-null   float64
 9   rr             70601 non-null   float64
 10  tage_festrrp   56675 non-null   float64
 11  substation     30787 non-null   float64
dtypes: float64(10), int64(1), str(1)
memory usage: 24.5 MB

In [7]:
klima["station"].nunique()

176

In [8]:
klima = klima.merge(
    tirol_stations[["id", "Stationsname", "Höhe [m]", "Startdatum", "Enddatum"]],
    left_on="station",
    right_on="id",
    how="left"
)

klima.head()

,time,station,tl_mittel,tlmax_mittel,tlmin_mittel,tage_frost,shneu_manu,tage_schdecke,sh_manu_max,rr,tage_festrrp,substation,id,Stationsname,Höhe [m],Startdatum,Enddatum
0,1900-01-01T00:00+00:00,8501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8501,Vils,836.0,1947-09-01 00:00:00+00:00,1977-12-01 00:00:00+00:00
1,1900-01-01T00:00+00:00,8800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8800,Achenkirch,905.0,1987-08-01 00:00:00+00:00,1998-06-01 00:00:00+00:00
2,1900-01-01T00:00+00:00,8805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8805,Achenkirch,904.0,1998-07-01 00:00:00+00:00,2020-05-01 00:00:00+00:00
3,1900-01-01T00:00+00:00,8806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8806,Achenkirch,931.0,2016-10-01 00:00:00+00:00,2100-12-31 00:00:00+00:00
4,1900-01-01T00:00+00:00,8807,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8807,Achenkirch,937.0,2020-06-01 00:00:00+00:00,2100-12-31 00:00:00+00:00

In [9]:
klima["Stationsname"].isna().sum()

np.int64(0)

In [10]:
temperatur_check = klima.groupby(
    ["station", "Stationsname", "Höhe [m]"]
)["tl_mittel"].count().sort_values(ascending=False)

temperatur_check.head(20)

station  Stationsname               Höhe [m]
39       Innsbruck Universität      578.0       1520
28       Galtür                     1587.0      1504
142      Kufstein                   490.0       1256
55       Lienz                      661.0       1157
61       Mayrhofen                  640.0       1086
76       Reutte                     841.8       1078
17000    Galtür                     1583.0      1075
146      Holzgau                    1092.0      1074
185      St.Jakob im Defereggental  1383.0      1052
11801    Innsbruck Universität      577.0       1044
136      Umhausen                   1035.0      1027
196      Patscherkofel              2251.0      1023
14300    St. Anton am Arlberg       1298.0      1020
9010     Kufstein                   492.0        972
50       Landeck                    795.6        967
119      St.Anton am Arlberg        1304.1       952
130      Sillian                    1081.4       926
87       Seefeld                    1181.9       904
175      Innsbruck Flughafen        578.0        903
16       Brenner                    1412.0       903
Name: tl_mittel, dtype: int64

In [11]:
parameter = [
    "tl_mittel",
    "tlmax_mittel",
    "tlmin_mittel",
    "tage_frost",
    "shneu_manu",
    "tage_schdecke",
    "sh_manu_max",
    "rr",
    "tage_festrrp"
]

daten_check = klima.groupby(
    ["station", "Stationsname", "Höhe [m]"]
)[parameter].count()

daten_check.head(20)

,,,tl_mittel,tlmax_mittel,tlmin_mittel,tage_frost,shneu_manu,tage_schdecke,sh_manu_max,rr,tage_festrrp
station,Stationsname,Höhe [m],,,,,,,,,
16,Brenner,1412.0,903,903,903,903,289,689,689,903,689
20,Ehrwald,982.0,649,649,649,649,288,413,413,649,424
28,Galtür,1587.0,1504,843,843,843,406,833,833,1503,844
38,Imst,773.0,878,872,872,870,296,668,668,879,669
39,Innsbruck Universität,578.0,1520,1487,1487,1487,1090,1171,1171,1520,1519
42,Jenbach,529.0,826,826,826,826,325,670,670,826,666
43,Kals,1352.4,893,892,888,887,523,766,766,901,759
50,Landeck,795.6,967,967,967,967,938,946,946,966,943
55,Lienz,661.0,1157,1061,1061,1030,778,1129,1129,1144,1026
61,Mayrhofen,640.0,1086,1086,1086,1086,283,834,834,1086,859
66,Obergurgl,1941.0,878,874,874,874,569,875,875,878,872
76,Reutte,841.8,1078,971,970,970,320,857,857,1078,861
87,Seefeld,1181.9,904,904,904,904,415,781,781,903,776
114,Zell am Ziller/Rohrberg,595.0,448,448,448,448,108,448,448,448,447
118,Kitzbühel,772.0,889,887,881,878,286,636,636,880,655
119,St.Anton am Arlberg,1304.1,952,948,948,947,314,731,731,947,734
121,Nauders,1330.2,807,807,807,807,803,806,806,806,803
126,Haiming,659.0,842,842,842,841,283,615,615,841,613
127,Rinn,924.1,861,860,860,827,340,626,626,861,626
130,Sillian,1081.4,926,883,882,882,335,735,736,927,733

In [12]:
temp_zeitraum = (
    klima.dropna(subset=["tl_mittel"])
    .groupby(["station", "Stationsname", "Höhe [m]"])["time"]
    .agg(["min", "max", "count"])
    .sort_values("count", ascending=False)
)

temp_zeitraum.head(20)

,,,min,max,count
station,Stationsname,Höhe [m],,,
39,Innsbruck Universität,578.0,1900-01-01T00:00+00:00,2026-08-01T00:00+00:00,1520
28,Galtür,1587.0,1901-01-01T00:00+00:00,2026-08-01T00:00+00:00,1504
142,Kufstein,490.0,1919-07-01T00:00+00:00,2026-08-01T00:00+00:00,1256
55,Lienz,661.0,1900-01-01T00:00+00:00,2026-08-01T00:00+00:00,1157
61,Mayrhofen,640.0,1936-01-01T00:00+00:00,2026-07-01T00:00+00:00,1086
76,Reutte,841.8,1936-01-01T00:00+00:00,2026-08-01T00:00+00:00,1078
17000,Galtür,1583.0,1900-01-01T00:00+00:00,1989-12-01T00:00+00:00,1075
146,Holzgau,1092.0,1936-01-01T00:00+00:00,2026-08-01T00:00+00:00,1074
185,St.Jakob im Defereggental,1383.0,1938-01-01T00:00+00:00,2026-08-01T00:00+00:00,1052
11801,Innsbruck Universität,577.0,1900-01-01T00:00+00:00,1986-12-01T00:00+00:00,1044
136,Umhausen,1035.0,1936-01-01T00:00+00:00,2026-07-01T00:00+00:00,1027
196,Patscherkofel,2251.0,1940-08-01T00:00+00:00,2026-08-01T00:00+00:00,1023
14300,St. Anton am Arlberg,1298.0,1900-01-01T00:00+00:00,2002-03-01T00:00+00:00,1020
9010,Kufstein,492.0,1919-07-01T00:00+00:00,2002-12-01T00:00+00:00,972
50,Landeck,795.6,1946-02-01T00:00+00:00,2026-08-01T00:00+00:00,967
119,St.Anton am Arlberg,1304.1,1938-02-01T00:00+00:00,2026-08-01T00:00+00:00,952
130,Sillian,1081.4,1948-01-01T00:00+00:00,2026-08-01T00:00+00:00,926
87,Seefeld,1181.9,1948-05-01T00:00+00:00,2026-08-01T00:00+00:00,904
175,Innsbruck Flughafen,578.0,1951-06-01T00:00+00:00,2026-08-01T00:00+00:00,903
16,Brenner,1412.0,1948-01-01T00:00+00:00,2026-08-01T00:00+00:00,903

In [13]:
schnee_zeitraum = (
    klima.dropna(subset=["tage_schdecke"])
    .groupby(["station", "Stationsname", "Höhe [m]"])["time"]
    .agg(["min", "max", "count"])
    .sort_values("count", ascending=False)
)

schnee_zeitraum.head(20)

,,,min,max,count
station,Stationsname,Höhe [m],,,
142,Kufstein,490.0,1923-01-01T00:00+00:00,2026-08-01T00:00+00:00,1200
39,Innsbruck Universität,578.0,1916-11-01T00:00+00:00,2026-08-01T00:00+00:00,1171
55,Lienz,661.0,1900-01-01T00:00+00:00,2026-08-01T00:00+00:00,1129
136,Umhausen,1035.0,1936-01-01T00:00+00:00,2026-08-01T00:00+00:00,1028
185,St.Jakob im Defereggental,1383.0,1939-11-01T00:00+00:00,2026-05-01T00:00+00:00,1026
50,Landeck,795.6,1946-02-01T00:00+00:00,2024-12-01T00:00+00:00,946
9010,Kufstein,492.0,1923-01-01T00:00+00:00,2002-12-01T00:00+00:00,917
11800,Innsbruck Flughafen,579.0,1951-06-01T00:00+00:00,2026-08-01T00:00+00:00,903
66,Obergurgl,1941.0,1953-01-01T00:00+00:00,2026-08-01T00:00+00:00,875
76,Reutte,841.8,1936-05-01T00:00+00:00,2008-08-01T00:00+00:00,857
146,Holzgau,1092.0,1936-01-01T00:00+00:00,2007-12-01T00:00+00:00,850
61,Mayrhofen,640.0,1936-12-01T00:00+00:00,2007-08-01T00:00+00:00,834
28,Galtür,1587.0,1939-01-01T00:00+00:00,2008-08-01T00:00+00:00,833
11400,Holzgau,1100.0,1936-01-01T00:00+00:00,2005-09-01T00:00+00:00,823
121,Nauders,1330.2,1958-06-01T00:00+00:00,2026-08-01T00:00+00:00,806
17700,St. Jakob im Defereggental,1385.0,1939-11-01T00:00+00:00,2007-10-01T00:00+00:00,805
196,Patscherkofel,2251.0,1940-08-01T00:00+00:00,2007-12-01T00:00+00:00,794
87,Seefeld,1181.9,1948-05-01T00:00+00:00,2026-07-01T00:00+00:00,781
43,Kals,1352.4,1951-05-01T00:00+00:00,2017-02-01T00:00+00:00,766
14630,Umhausen,1041.0,1936-01-01T00:00+00:00,2003-09-01T00:00+00:00,753

In [14]:
klima["time"] = pd.to_datetime(klima["time"], utc=True)

analyse = klima[
    (klima["time"] >= "1970-01-01") &
    (klima["time"] <= "2025-12-31")
].copy()

analyse.shape

(118272, 17)

In [15]:
vollstaendigkeit = analyse.groupby(
    ["station", "Stationsname", "Höhe [m]"]
)[parameter].count()

vollstaendigkeit.head(20)

,,,tl_mittel,tlmax_mittel,tlmin_mittel,tage_frost,shneu_manu,tage_schdecke,sh_manu_max,rr,tage_festrrp
station,Stationsname,Höhe [m],,,,,,,,,
16,Brenner,1412.0,661,661,661,661,289,455,455,661,455
20,Ehrwald,982.0,641,641,641,641,288,413,413,641,424
28,Galtür,1587.0,669,669,669,669,335,464,464,671,464
38,Imst,773.0,649,649,649,648,289,447,447,654,447
39,Innsbruck Universität,578.0,672,672,672,672,588,672,672,672,671
42,Jenbach,529.0,641,641,641,641,321,489,489,641,485
43,Kals,1352.4,661,661,661,661,415,543,543,670,537
50,Landeck,795.6,672,672,672,672,659,659,659,672,657
55,Lienz,661.0,672,672,672,672,658,669,669,672,669
61,Mayrhofen,640.0,671,671,671,671,283,451,451,671,451
66,Obergurgl,1941.0,668,668,668,668,562,664,664,666,663
76,Reutte,841.8,672,672,672,672,320,464,464,672,464
87,Seefeld,1181.9,639,639,639,639,409,518,518,639,513
114,Zell am Ziller/Rohrberg,595.0,276,276,276,276,108,276,276,276,275
118,Kitzbühel,772.0,611,611,611,611,277,388,388,606,388
119,St.Anton am Arlberg,1304.1,672,672,672,672,309,460,460,670,461
121,Nauders,1330.2,660,660,660,660,660,660,660,660,659
126,Haiming,659.0,671,671,671,670,283,451,451,671,451
127,Rinn,924.1,663,663,663,663,337,467,467,663,467
130,Sillian,1081.4,668,668,668,668,335,487,488,669,488

In [16]:
vollstaendigkeit_prozent = (vollstaendigkeit / 672 * 100).round(1)

vollstaendigkeit_prozent.head(20)

,,,tl_mittel,tlmax_mittel,tlmin_mittel,tage_frost,shneu_manu,tage_schdecke,sh_manu_max,rr,tage_festrrp
station,Stationsname,Höhe [m],,,,,,,,,
16,Brenner,1412.0,98.4,98.4,98.4,98.4,43.0,67.7,67.7,98.4,67.7
20,Ehrwald,982.0,95.4,95.4,95.4,95.4,42.9,61.5,61.5,95.4,63.1
28,Galtür,1587.0,99.6,99.6,99.6,99.6,49.9,69.0,69.0,99.9,69.0
38,Imst,773.0,96.6,96.6,96.6,96.4,43.0,66.5,66.5,97.3,66.5
39,Innsbruck Universität,578.0,100.0,100.0,100.0,100.0,87.5,100.0,100.0,100.0,99.9
42,Jenbach,529.0,95.4,95.4,95.4,95.4,47.8,72.8,72.8,95.4,72.2
43,Kals,1352.4,98.4,98.4,98.4,98.4,61.8,80.8,80.8,99.7,79.9
50,Landeck,795.6,100.0,100.0,100.0,100.0,98.1,98.1,98.1,100.0,97.8
55,Lienz,661.0,100.0,100.0,100.0,100.0,97.9,99.6,99.6,100.0,99.6
61,Mayrhofen,640.0,99.9,99.9,99.9,99.9,42.1,67.1,67.1,99.9,67.1
66,Obergurgl,1941.0,99.4,99.4,99.4,99.4,83.6,98.8,98.8,99.1,98.7
76,Reutte,841.8,100.0,100.0,100.0,100.0,47.6,69.0,69.0,100.0,69.0
87,Seefeld,1181.9,95.1,95.1,95.1,95.1,60.9,77.1,77.1,95.1,76.3
114,Zell am Ziller/Rohrberg,595.0,41.1,41.1,41.1,41.1,16.1,41.1,41.1,41.1,40.9
118,Kitzbühel,772.0,90.9,90.9,90.9,90.9,41.2,57.7,57.7,90.2,57.7
119,St.Anton am Arlberg,1304.1,100.0,100.0,100.0,100.0,46.0,68.5,68.5,99.7,68.6
121,Nauders,1330.2,98.2,98.2,98.2,98.2,98.2,98.2,98.2,98.2,98.1
126,Haiming,659.0,99.9,99.9,99.9,99.7,42.1,67.1,67.1,99.9,67.1
127,Rinn,924.1,98.7,98.7,98.7,98.7,50.1,69.5,69.5,98.7,69.5
130,Sillian,1081.4,99.4,99.4,99.4,99.4,49.9,72.5,72.6,99.6,72.6

In [17]:
geeignete_stationen = vollstaendigkeit_prozent[
    (vollstaendigkeit_prozent["tl_mittel"] >= 90) &
    (vollstaendigkeit_prozent["tage_schdecke"] >= 90)
]

geeignete_stationen

,,,tl_mittel,tlmax_mittel,tlmin_mittel,tage_frost,shneu_manu,tage_schdecke,sh_manu_max,rr,tage_festrrp
station,Stationsname,Höhe [m],,,,,,,,,
39,Innsbruck Universität,578.0,100.0,100.0,100.0,100.0,87.5,100.0,100.0,100.0,99.9
50,Landeck,795.6,100.0,100.0,100.0,100.0,98.1,98.1,98.1,100.0,97.8
55,Lienz,661.0,100.0,100.0,100.0,100.0,97.9,99.6,99.6,100.0,99.6
66,Obergurgl,1941.0,99.4,99.4,99.4,99.4,83.6,98.8,98.8,99.1,98.7
121,Nauders,1330.2,98.2,98.2,98.2,98.2,98.2,98.2,98.2,98.2,98.1
136,Umhausen,1035.0,100.0,100.0,100.0,100.0,80.5,100.0,100.0,100.0,99.9
138,Prutz,871.0,99.9,99.9,99.9,99.9,80.2,99.6,99.6,100.0,99.4
142,Kufstein,490.0,100.0,100.0,100.0,100.0,97.6,99.9,99.9,100.0,98.2
185,St.Jakob im Defereggental,1383.0,98.8,99.6,98.8,98.7,80.1,99.1,99.3,99.6,98.2

In [18]:
def hoehenklasse(hoehe):
    if hoehe < 800:
        return "Tal (<800 m)"
    elif hoehe <= 1300:
        return "Mittellage (800-1300 m)"
    else:
        return "Hochlage (>1300 m)"

analyse["Höhenklasse"] = analyse["Höhe [m]"].apply(hoehenklasse)

In [19]:
station_ids = geeignete_stationen.index.get_level_values("station")

tirol_final = analyse[
    analyse["station"].isin(station_ids)
].copy()

tirol_final.shape

(6048, 18)

In [20]:
tirol_final[parameter].isna().sum()

tl_mittel         25
tlmax_mittel      20
tlmin_mittel      25
tage_frost        26
shneu_manu       647
tage_schdecke     46
sh_manu_max       45
rr                21
tage_festrrp      70
dtype: int64

In [21]:
tirol_final["Jahr"] = tirol_final["time"].dt.year
tirol_final["Monat"] = tirol_final["time"].dt.month

tirol_final[["time", "Jahr", "Monat"]].head()

                            time  Jahr  Monat
147984 1970-01-01 00:00:00+00:00  1970      1
147987 1970-01-01 00:00:00+00:00  1970      1
147988 1970-01-01 00:00:00+00:00  1970      1
147990 1970-01-01 00:00:00+00:00  1970      1
147996 1970-01-01 00:00:00+00:00  1970      1

In [22]:
jahresdaten = tirol_final.groupby(
    ["station", "Stationsname", "Höhe [m]", "Höhenklasse", "Jahr"]
).agg({
    "tl_mittel": "mean",
    "tlmax_mittel": "mean",
    "tlmin_mittel": "mean",
    "tage_frost": "sum",
    "shneu_manu": "sum",
    "tage_schdecke": "sum",
    "sh_manu_max": "max",
    "rr": "sum"
}).reset_index()

jahresdaten.head()

,station,Stationsname,Höhe [m],Höhenklasse,Jahr,tl_mittel,tlmax_mittel,tlmin_mittel,tage_frost,shneu_manu,tage_schdecke,sh_manu_max,rr
0,39,Innsbruck Universität,578.0,Tal (<800 m),1970,8.125000,13.366667,3.916667,109.0,166.0,76.0,35.0,1109.0
1,39,Innsbruck Universität,578.0,Tal (<800 m),1971,8.066667,14.258333,3.816667,109.0,135.0,95.0,27.0,752.0
2,39,Innsbruck Universität,578.0,Tal (<800 m),1972,8.358333,14.391667,4.258333,92.0,43.0,67.0,17.0,826.0
3,39,Innsbruck Universität,578.0,Tal (<800 m),1973,8.075000,13.983333,4.116667,124.0,157.0,86.0,18.0,848.0
4,39,Innsbruck Universität,578.0,Tal (<800 m),1974,8.975000,14.891667,4.950000,67.0,0.0,35.0,25.0,869.0

In [23]:
monate_pro_jahr = tirol_final.groupby(
    ["station", "Stationsname", "Jahr"]
)[parameter].count()

monate_pro_jahr.head(20)

                                    tl_mittel  tlmax_mittel  tlmin_mittel  \
station Stationsname          Jahr
39      Innsbruck Universität 1970         12            12            12
                              1971         12            12            12
                              1972         12            12            12
                              1973         12            12            12
                              1974         12            12            12
                              1975         12            12            12
                              1976         12            12            12
                              1977         12            12            12
                              1978         12            12            12
                              1979         12            12            12
                              1980         12            12            12
                              1981         12            12            12
                              1982         12            12            12
                              1983         12            12            12
                              1984         12            12            12
                              1985         12            12            12
                              1986         12            12            12
                              1987         12            12            12
                              1988         12            12            12
                              1989         12            12            12

                                    tage_frost  shneu_manu  tage_schdecke  \
station Stationsname          Jahr
39      Innsbruck Universität 1970          12          12             12
                              1971          12          12             12
                              1972          12          12             12
                              1973          12          12             12
                              1974          12           0             12
                              1975          12           0             12
                              1976          12           0             12
                              1977          12           0             12
                              1978          12           0             12
                              1979          12           0             12
                              1980          12           0             12
                              1981          12          12             12
                              1982          12          12             12
                              1983          12          12             12
                              1984          12          12             12
                              1985          12          12             12
                              1986          12          12             12
                              1987          12          12             12
                              1988          12          12             12
                              1989          12          12             12

                                    sh_manu_max  rr  tage_festrrp
station Stationsname          Jahr
39      Innsbruck Universität 1970           12  12            12
                              1971           12  12            12
                              1972           12  12            12
                              1973           12  12            12
                              1974           12  12            12
                              1975           12  12            12
                              1976           12  12            12
                              1977           12  12            12
                              1978           12  12            12
                              1979           12  12            12
                              1980           12  12            12
                              1981           12  12            12
                              1982           12  12            12
                              1983           12  12            12
                              1984           12  12            12
                              1985           12  12            12
                              1986           12  12            12
                              1987           12  12            12
                              1988           12  12            12
                              1989           12  12            12

In [24]:
jahresdaten = tirol_final.groupby(
    ["station", "Stationsname", "Höhe [m]", "Höhenklasse", "Jahr"]
).agg(
    tl_mittel=("tl_mittel", "mean"),
    tlmax_mittel=("tlmax_mittel", "mean"),
    tlmin_mittel=("tlmin_mittel", "mean"),
    tage_frost=("tage_frost", lambda x: x.sum(min_count=10)),
    shneu_manu=("shneu_manu", lambda x: x.sum(min_count=10)),
    tage_schdecke=("tage_schdecke", lambda x: x.sum(min_count=10)),
    sh_manu_max=("sh_manu_max", "max"),
    rr=("rr", lambda x: x.sum(min_count=10))
).reset_index()

jahresdaten.head(10)

,station,Stationsname,Höhe [m],Höhenklasse,Jahr,tl_mittel,tlmax_mittel,tlmin_mittel,tage_frost,shneu_manu,tage_schdecke,sh_manu_max,rr
0,39,Innsbruck Universität,578.0,Tal (<800 m),1970,8.125000,13.366667,3.916667,109.0,166.0,76.0,35.0,1109.0
1,39,Innsbruck Universität,578.0,Tal (<800 m),1971,8.066667,14.258333,3.816667,109.0,135.0,95.0,27.0,752.0
2,39,Innsbruck Universität,578.0,Tal (<800 m),1972,8.358333,14.391667,4.258333,92.0,43.0,67.0,17.0,826.0
3,39,Innsbruck Universität,578.0,Tal (<800 m),1973,8.075000,13.983333,4.116667,124.0,157.0,86.0,18.0,848.0
4,39,Innsbruck Universität,578.0,Tal (<800 m),1974,8.975000,14.891667,4.950000,67.0,NaN,35.0,25.0,869.0
5,39,Innsbruck Universität,578.0,Tal (<800 m),1975,8.641667,14.691667,4.700000,101.0,NaN,73.0,30.0,893.0
6,39,Innsbruck Universität,578.0,Tal (<800 m),1976,8.683333,14.950000,4.433333,104.0,NaN,53.0,33.0,763.0
7,39,Innsbruck Universität,578.0,Tal (<800 m),1977,8.975000,14.941667,5.000000,82.0,NaN,66.0,43.0,870.0
8,39,Innsbruck Universität,578.0,Tal (<800 m),1978,7.808333,13.883333,3.841667,109.0,NaN,75.0,22.0,838.0
9,39,Innsbruck Universität,578.0,Tal (<800 m),1979,8.475000,14.291667,4.558333,87.0,NaN,59.0,13.0,1128.0

In [25]:
jahresdaten.isna().sum()

station           0
Stationsname      0
Höhe [m]          0
Höhenklasse       0
Jahr              0
tl_mittel         0
tlmax_mittel      0
tlmin_mittel      0
tage_frost        5
shneu_manu       54
tage_schdecke     5
sh_manu_max       1
rr                4
dtype: int64

In [26]:
analyse_1940 = klima[
    (klima["time"] >= "1940-01-01") &
    (klima["time"] <= "2025-12-31")
].copy()

monate_1940 = 86 * 12

check_1940 = analyse_1940.groupby(
    ["station", "Stationsname", "Höhe [m]"]
)[["tl_mittel", "tage_schdecke"]].count()

check_1940_prozent = (check_1940 / monate_1940 * 100).round(1)

geeignet_1940 = check_1940_prozent[
    (check_1940_prozent["tl_mittel"] >= 90) &
    (check_1940_prozent["tage_schdecke"] >= 90)
]

geeignet_1940

                                            tl_mittel  tage_schdecke
station Stationsname              Höhe [m]
39      Innsbruck Universität     578.0         100.0          100.0
50      Landeck                   795.6          92.9           91.7
55      Lienz                     661.0          94.8           94.4
136     Umhausen                  1035.0         94.2           94.2
142     Kufstein                  490.0          97.1           96.7
185     St.Jakob im Defereggental 1383.0         98.8           98.7

In [27]:
analyse_1950 = klima[
    (klima["time"] >= "1950-01-01") &
    (klima["time"] <= "2025-12-31")
].copy()

monate_1950 = 76 * 12

check_1950 = analyse_1950.groupby(
    ["station", "Stationsname", "Höhe [m]"]
)[["tl_mittel", "tage_schdecke"]].count()

check_1950_prozent = (check_1950 / monate_1950 * 100).round(1)

geeignet_1950 = check_1950_prozent[
    (check_1950_prozent["tl_mittel"] >= 90) &
    (check_1950_prozent["tage_schdecke"] >= 90)
]

geeignet_1950

                                            tl_mittel  tage_schdecke
station Stationsname              Höhe [m]
39      Innsbruck Universität     578.0         100.0          100.0
50      Landeck                   795.6         100.0           98.6
55      Lienz                     661.0         100.0           99.6
66      Obergurgl                 1941.0         95.4           95.2
136     Umhausen                  1035.0        100.0          100.0
142     Kufstein                  490.0         100.0           99.9
185     St.Jakob im Defereggental 1383.0         99.1           99.3

In [28]:
analyse_1960 = klima[
    (klima["time"] >= "1960-01-01") &
    (klima["time"] <= "2025-12-31")
].copy()

monate_1960 = 66 * 12

check_1960 = analyse_1960.groupby(
    ["station", "Stationsname", "Höhe [m]"]
)[["tl_mittel", "tage_schdecke"]].count()

check_1960_prozent = (check_1960 / monate_1960 * 100).round(1)

geeignet_1960 = check_1960_prozent[
    (check_1960_prozent["tl_mittel"] >= 90) &
    (check_1960_prozent["tage_schdecke"] >= 90)
]

geeignet_1960

                                            tl_mittel  tage_schdecke
station Stationsname              Höhe [m]
39      Innsbruck Universität     578.0         100.0          100.0
50      Landeck                   795.6         100.0           98.4
55      Lienz                     661.0         100.0           99.5
66      Obergurgl                 1941.0         99.2           99.0
121     Nauders                   1330.2         98.5           98.5
136     Umhausen                  1035.0        100.0          100.0
142     Kufstein                  490.0         100.0           99.9
185     St.Jakob im Defereggental 1383.0         99.0           99.2